language: python
python:
- '3.7'
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION xarray pytest
  codecov
- conda activate test-environment
- python setup.py install
- conda install jupyter_sphinx -c conda-forge
script:
- pytest tests
env:
- CODECOV_TOKEN=eec0bd7a-c143-43df-89ab-e27d5c67dffd
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Zp5CtotiR0Thjgfy8F3L4xU928wBVPEGQwW/YWAKSTlS4plwySj0PDbpqs8XN0QoCLvkN/Hy+IH1nSrxjRaByYsoJVL8FP7/yfVLLQBqNCo+plZSvmDD38ToQDcas4u82r06mWoZJow9SYTvxi14ATMU/3Q4Kec1/EI6s0jbydlTu2s21mvO19s/WHZHjsQo8vOgZ9aDPpXiQVuwpwStTXJMp6dKB6lfwH52SjCPQGbFg/xd0+qCjbY3I/61eA98Ehlei5UH9vm3oiTtBppJNDEFDvWr/gGF1CLnc1v3OedEIQif5KIKIc0Fn4l+DnpeEnQ3sJOEqg2S9yPIgMUU3Ehx1WCpjQ6Em+6uiGc+rpIDgDGcu/6WngtvVPw0V0MuoINwMGPvKvwrRbIPYxWE6D8TNJ/14gIc3dfyVLK0Fo4Eh5DjcpHhmNd6cakKee/+p0VTvPUkM8sA77/PiWJaIoeo4OjTFuVwsRvP8Ab1J+UwKPzqAU1eD9sgbNJifHgkwxLPdLFp8BmQVNw83MKtTV+2nyDN3/x+AZbws85S/NmFgNWLHeV0s4MmUe+XyKQE7cwPAGM1+F80LU6CaAzGefFekMWFJ+Jynkoh0KTn3Gt0F5UbUi1zonyJvOnDO1R/Eed9osD5qhGVaVkykEIJJjnRZgtRCrv4SxP7M8AQp1E=
  on:
    branch: v0.2.10
